#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ujson
Version  : 4.2.0
Release  : 20
URL      : https://files.pythonhosted.org/packages/df/69/e8f615e1a779e2d2d23d29d56dc55bbb1db2a828f0ef36d10bc697d63968/ujson-4.2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/df/69/e8f615e1a779e2d2d23d29d56dc55bbb1db2a828f0ef36d10bc697d63968/ujson-4.2.0.tar.gz
Summary  : Ultra fast JSON encoder and decoder for Python
Group    : Development/Tools
License  : BSD-3-Clause
Requires: ujson-license = %{version}-%{release}
Requires: ujson-python = %{version}-%{release}
Requires: ujson-python3 = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-scons

%description
# UltraJSON
[![PyPI version](https://img.shields.io/pypi/v/ujson.svg?logo=pypi&logoColor=FFE873)](https://pypi.org/project/ujson)
[![Supported Python versions](https://img.shields.io/pypi/pyversions/ujson.svg?logo=python&logoColor=FFE873)](https://pypi.org/project/ujson)
[![PyPI downloads](https://img.shields.io/pypi/dm/ujson.svg)](https://pypistats.org/packages/ujson)
[![GitHub Actions status](https://github.com/ultrajson/ultrajson/workflows/Test/badge.svg)](https://github.com/ultrajson/ultrajson/actions)
[![Travis CI status](https://travis-ci.com/ultrajson/ultrajson.svg?branch=main)](https://travis-ci.com/ultrajson/ultrajson)
[![codecov](https://codecov.io/gh/ultrajson/ultrajson/branch/main/graph/badge.svg)](https://codecov.io/gh/ultrajson/ultrajson)
[![DOI](https://zenodo.org/badge/1418941.svg)](https://zenodo.org/badge/latestdoi/1418941)
[![Code style: Black](https://img.shields.io/badge/code%20style-Black-000000.svg)](https://github.com/psf/black)

%package license
Summary: license components for the ujson package.
Group: Default

%description license
license components for the ujson package.


%package python
Summary: python components for the ujson package.
Group: Default
Requires: ujson-python3 = %{version}-%{release}

%description python
python components for the ujson package.


%package python3
Summary: python3 components for the ujson package.
Group: Default
Requires: python3-core
Provides: pypi(ujson)

%description python3
python3 components for the ujson package.


%prep
%setup -q -n ujson-4.2.0
cd %{_builddir}/ujson-4.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1632414685
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ujson
cp %{_builddir}/ujson-4.2.0/LICENSE.txt %{buildroot}/usr/share/package-licenses/ujson/0a8a0c4dd38dfac034078c7f3e0c16ff489d6646
cp %{_builddir}/ujson-4.2.0/deps/double-conversion/COPYING %{buildroot}/usr/share/package-licenses/ujson/8d434c9c1704b544a8b0652efbc323380b67f9bc
cp %{_builddir}/ujson-4.2.0/deps/double-conversion/LICENSE %{buildroot}/usr/share/package-licenses/ujson/8d434c9c1704b544a8b0652efbc323380b67f9bc
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ujson/0a8a0c4dd38dfac034078c7f3e0c16ff489d6646
/usr/share/package-licenses/ujson/8d434c9c1704b544a8b0652efbc323380b67f9bc

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
